
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author najam
 */
public class DeleteGrp extends javax.swing.JFrame {
Vector<String> colName;
Vector<Vector<Object>> tbData;
GroupPanel refg;
    /**
     * Creates new form DeleteGrp
     */
    public DeleteGrp(GroupPanel ref) {
        this.refg=ref; 
        initComponents();
        setTable();
    }

    private DeleteGrp() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));

        jLabel1.setBackground(new java.awt.Color(0, 204, 204));
        jLabel1.setFont(new java.awt.Font("Eras Bold ITC", 1, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Delete Groups");

        jButton1.setBackground(new java.awt.Color(255, 102, 102));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jButton1)
                .addGap(78, 78, 78)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(0, 11, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jTable1.setBackground(new java.awt.Color(255, 153, 153));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Title 1"
            }
        ));
        jTable1.setRowHeight(40);
        jTable1.setRowMargin(3);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel2.setFont(new java.awt.Font("Eras Bold ITC", 1, 13)); // NOI18N
        jLabel2.setText("Select the Group to Delete");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(jLabel2)
                .addContainerGap(103, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        refg.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed
 public int getGid(String col1,String col2) throws Exception
    {
        String sql = "Select * from Groups where GName=? and Type=?";
        int id=0;
        try (Connection conn = this.connectDatabase();
                PreparedStatement pstmt = conn.prepareStatement(sql)) {
            
      pstmt.setString(1,col1);
      pstmt.setString(2,col2);
      ResultSet rs = pstmt.executeQuery();
      while(rs.next())
      {
          id= rs.getInt("GId");}
         
     } 
    return id;
    
    }
 public void deleteQuery(int gid,String table) throws Exception
 {
     String sql = "delete from "+table+" where GId=?";
            
        
        try (Connection conn = this.connectDatabase();
                PreparedStatement pstmt = conn.prepareStatement(sql)) {
            
      pstmt.setInt(1,gid);
     
     
      int rs = pstmt.executeUpdate();
        }
   
 }
 
 public boolean ifTableExists(int gid,String table) throws Exception
 {  
      String sql = "select * from "+table+" where GId=?";
            
        
        try (Connection conn = this.connectDatabase();
                PreparedStatement pstmt = conn.prepareStatement(sql)) {
            
      pstmt.setInt(1,gid);
     
     
          ResultSet rs = pstmt.executeQuery();
          if(rs.next())
              return true;
        }
     
     return false;
}
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        JTable temp = (JTable) evt.getSource();
        int row = temp.getSelectedRow();
        
        String Name = (String) temp.getModel().getValueAt(row, 0);
        String Type = (String) temp.getModel().getValueAt(row, 1);
    try {
         int input = JOptionPane.showConfirmDialog(null, "Do you want to Delete "+Name+" ?");
         if(input==0)
         {
        int gid=getGid(Name,Type);
        if(ifTableExists(gid,"Groups"))
        { deleteQuery(gid,"Groups");
            System.out.println("deleted grp");
                }
        if(ifTableExists(gid,"GMembers"))
        { deleteQuery(gid,"GMembers");
          System.out.println("deleted grpMembers");}
        if(ifTableExists(gid,"GBills"))
        {deleteQuery(gid,"GBills");
          System.out.println("deleted grpBills");}
        if(ifTableExists(gid,"GBillMembers"))
        { deleteQuery(gid,"GBillMembers");
          System.out.println("deleted grpBillMemebrs");}
         this.dispose();
         refg.setTable();
         refg.setVisible(true);}
    } catch (Exception ex) {
        Logger.getLogger(DeleteGrp.class.getName()).log(Level.SEVERE, null, ex);
    }
                
    }//GEN-LAST:event_jTable1MouseClicked
           public static  Connection connectDatabase() throws Exception
{
    Connection con;
    PreparedStatement stmt;
    
    
   
        Class.forName("com.mysql.jdbc.Driver");
        con = DriverManager.getConnection("jdbc:mysql://localhost:8080/splitwise", "root", "");
    
        return con;
       
    
}
    public DefaultTableModel makeTable(ResultSet rs)
    {   
        
        
        try {
               
            ResultSetMetaData rsMeta = rs.getMetaData();
            
            int colCount = rsMeta.getColumnCount();
           
             colName = new Vector<String>();
            for(int i=2;i<=colCount;i++)
            {
                
                colName.add(rsMeta.getColumnName(i));
            }
            
            tbData = new Vector<Vector<Object>>();
            
            while(rs.next())
            {
                Vector<Object> row = new Vector<Object>();
                
                for(int i = 2;i<=colCount;i++)
                {
                    row.add(rs.getObject(i));
                }
                tbData.add(row);
            }
            
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        
        return new DefaultTableModel(tbData, colName);
    }
        
    public void setTable()
    {
              String sql = "Select * from Groups";
        
        try (Connection conn = this.connectDatabase();
                PreparedStatement pstmt = conn.prepareStatement(sql)) {
            
       ResultSet rs = pstmt.executeQuery();
         
        DefaultTableModel model=this.makeTable(rs);
        jTable1.setModel(model);
     

        
   
              
            
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        } catch (Exception ex) {
            Logger.getLogger(AddGBill.class.getName()).log(Level.SEVERE, null, ex);
        } }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeleteGrp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeleteGrp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeleteGrp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeleteGrp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeleteGrp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
